baseURL = "https://slglobal.org/"
languageCode = "en-us"
title = "SLGlobal — Senior Leadership Global"
publishDir = "public"
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
